name: simple_pdf_compression
description: "Compress a PDF - nothing more"
version: 0.0.1
repository: https://github.com/shmink/flutter_simple_pdf_compression

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pdfx: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
