name: simple_pdf_compression
description: "Compress PDFs in Flutter with ease. Uses a smarter algorithm to balance file size and quality for optimal compression results."
version: 0.0.2
repository: https://github.com/WithWise/flutter_simple_pdf_compression

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pdfx: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
